website/Transport/urls.py
from django.conf.urls import url
from . import views
from mylogin import views as logviews
app_name = 'Transport'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', logviews.register, name='register'),
    url(r'^login/$', logviews.login_user, name='login_user'),
    url(r'^register/success/$',logviews.register_success),
    url(r'^logout_user/$', logviews.logout_user, name='logout_user'),
    #url(r'logout_user/$', views.new_login, name='new_login'),

    url(r'^allpassengers/',views.allpassengers, name='allpassengers'),    
    url(r'^alldrivers/',views.alldrivers, name='alldrivers'),
    url(r'^allvehicles/',views.allvehicles,name='allvehicles'),    
    url(r'^passenger_details/(?P<name_id>[1-6])/$',views.passenger_details,name="passenger_details"),
    url(r'^driver_details/(?P<name_id>car_[1-6])/$',views.driver_details,name="driver_details"),#### not used....
    url(r'^vehicle_details/(?P<name_id>car_[1-6])/$',views.vehicle_details,name="vehicle_details"),
    ####
    url(r'^update_driver/(?P<name_id>car_[1-6])/$',views.update_driver,name="update_driver"),
    url(r'^aboutus/$',views.aboutus,name='aboutus'),
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Transport/', include('Transport.urls')),
    url(r'^', include('Transport.urls')),
    #url(r'^reset/password_reset/$','django.contrib.auth.views.password_reset',name = 'reset_password_reset1'),
    url(r'^locate/', include('locate_me.urls')),
]

website/Transport/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import Permission, User
from django.db import models
from datetime import datetime
#from geoposition.fields import GeopositionField

# Create your models here.

class My_user(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    My_user_gender      = models.CharField(max_length=1, choices=GENDER_CHOICES,default=None)
    My_user_name        = models.CharField(max_length=250,default=None)
    My_user_phone       = models.IntegerField(default=None)
    My_user_addr        = models.CharField(max_length=250,default=None)
    My_user_email       = models.CharField(max_length=250,default=None)
    My_user_dateOfBirth = models.DateField(default=None,null=True)#To know the age of user
    def __str__(self):
        return '#'+self.My_user_name

class Vehicle(models.Model):#Stores information about vehicles
    Vehicle_name      = models.CharField(max_length=200,default=None)
    Vehicle_latitude  = models.FloatField(default=None)#latitude of vehicle
    Vehicle_longitude = models.FloatField(default=None)#longitude of vehicle
    Vehicle_rc        = models.CharField(max_length=200,default=None)#rc of the vehicle
    Vehicle_active    = models.BooleanField(default=None)#status of vehicle
    def __str__(self):
        return '@'+self.Vehicle_rc

class Driver(models.Model):#stores all driver details
    Driver_My_user        = models.ForeignKey(My_user,on_delete=models.CASCADE, default=0,blank=True)#to get all details from My user
    Driver_currentVehicle = models.ForeignKey(Vehicle,on_delete=models.CASCADE, default=0)
    Driver_liscence       = models.CharField(max_length=20,default=None)
    Driver_longitude      = models.FloatField(default=None,null=True)#longitude of driver
    Driver_latitude       = models.FloatField(default=None,null=True)#latitude  of driver
    #driver_currentVehicle gets current detail of vehicle driver
    def __str__(self):
        return '!'+self.Driver_My_user.My_user_name

class Passenger(models.Model):#stores all passangers details
    Passenger_My_user   = models.ForeignKey(My_user,on_delete=models.CASCADE, default=0)#to get all details from My user
    Passenger_latitude  = models.FloatField(default=None)#current latitude of passenger
    Passenger_longitude = models.FloatField(default=None)#current longitude of passenger
    Passenger_active    = models.BooleanField(default=None)#
    def __str__(self):
        return '$'+self.Passenger_My_user.My_user_name

class Valid_stop(models.Model):#This model stores all the valid stops
    Valid_stop_name      = models.CharField(max_length=50,default=None)#name of the stops
    Valid_stop_latitude  = models.FloatField(default=None)#latitude of valid stops
    Valid_stop_longitude = models.FloatField(default=None)#longitude of valid stops
    def __str__(self):
        return '%'+self.Valid_stop_name

class Booking(models.Model):#Stores all the information about bookings
    #Booking_startpoint  = models.ForeignKey(Valid_stop,default=0,on_delete=models.CASCADE,related_name='%(class)s_starting_point')#starting point of booking
    #Booking_destination = models.ForeignKey(Valid_stop, default=0,on_delete=models.CASCADE,related_name='%(class)s_destination_point')#ending point of booking
    Booking_startpoint  = models.CharField(max_length = 50,default=None)#starting point of booking
    Booking_destination = models.CharField(max_length = 50,default=None)#ending point of booking
    Booking_date        = models.DateTimeField(auto_now_add=True)
    Booking_passenger   = models.ForeignKey(Passenger, default=0,on_delete=models.CASCADE)#passanger
    Booking_vehicle     = models.ForeignKey(Vehicle,null=True,on_delete=models.CASCADE,blank=True)#vehicle booked
    Booking_status      = models.CharField(max_length=50,default='Pending')
    #booking_driver      = models.ForeignKey(driver,on_delete=models.CASCADE)#driver of the vehicle at the time of booking
    def __str__(self):
        return '^'+str(self.Booking_date)

class updatedriver(models.Model):
    drivername = models.CharField(max_length =100,default = None)
    driveremail = models.CharField(max_length =100,default = None)
    driveraddr = models.CharField(max_length =100,default = None)
    driverphone = models.CharField(max_length =100,default = None)

website/Transport/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UpdateDriver(forms.ModelForm):
   	class Meta:
 		model = updatedriver
 		fields = ['drivername','driveremail','driveraddr','driverphone']
#forms.py

website/Transport/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from Transport.models import *
from Transport.forms import *
from django import forms
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import pyrebase
config = {
    "apiKey": "AIzaSyAQHHnCqr-3FajALfmpg19PS44fsB6XkBA",
    "authDomain": "itsystems-162415.firebaseapp.com",
    "databaseURL": "https://itsystems-162415.firebaseio.com",
    "storageBucket" : "itsystems-162415.appspot.com"
  };
firebase = pyrebase.initialize_app(config);
db = firebase.database()

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)

                return render(request, 'Transport/index.html')
    context = {
        "form": form,
    }
    return render(request, 'Transport/register.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'Transport/index.html')
            else:
                return render(request, 'mylogin/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'mylogin/login.html', {'error_message': 'Invalid login'})
    return render(request, 'Transport/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'Transport/login.html', context)


def new_login(request):
    return render(request,'Transport/loggyn.html',{})     

def index(request):

   if not request.user.is_authenticated():
    return render(request,'mylogin/login.html')

   else:
        fire_vehi = db.child("My_user/Driver/").get()
        fire_rider = db.child("My_user/Rider/").get()
        # drivers    = Driver.objects.all()  
        # vehicles   = Vehicle.objects.all()                       
        passengers  = [[p.key(),p.val()] for p in fire_rider.each()]
        passengers = filter(lambda a: a[1]!= None, passengers)
        context    = {
                    # "drivers"   :drivers,
                    # "passengers":passengers,
                    # "vehicles"  :vehicles,
                    "drivs" : [p.val() for p in fire_vehi.each()],
                    "riders"  : passengers

                 }
        context['drivs'] = filter(lambda a: a!= None, context['drivs'])
        # print passengers[0]
        return render(request,'Transport/index.html',context)

     
@login_required
def allpassengers(request):                                     #displays all passengers
    users = db.child("My_user/Rider").get()
    use = [[p.key(),p.val()] for p in users.each() if p.val() != None]
    context = {
    "users" : use
    }
    print use
    return render(request,"Transport/passengers.html",context)

@login_required
def alldrivers(request):                                        #display all drivers
    users = db.child("My_user/Driver/").get()
    context = {
    "users" : [p.val() for p in users.each()]
    }
    return render(request, "Transport/drivers.html",context)

@login_required
def allvehicles(request):
    vehicles = db.child("My_user/Driver/").get()
    # vehicles = Vehicle.objects.all()                            #gets all vehicle details
    #vehicles = Vehicle.objects.all().count();
    # print vehicles
    context  = {                    
        "vehicles":[p.val() for p in vehicles.each()],
    }
    return render(request,"Transport/vehicles.html",context)

@login_required
def driver_details(request,name_id):                            #Details of driver with name_id as id
    driver  = Driver.objects.get(id=name_id)
    context = {
    "driver" : driver,
    }
    return render(request,"Transport/driver.html",context)

@login_required
def vehicle_details(request,name_id):                           #Details of vehicle with id name_id
        #vehicle = Vehicle.objects.get(id=name_id)
        print name_id
        vehicle = db.child("My_user/Driver/"+str(name_id)).get()
        riders = db.child("My_user/Rider/").get()
        l = [[p.key(),p.val()] for p in riders.each()]
        l = filter(lambda a: a[1]!= None, l)
        books = []
        try:
            # bookings  = Booking.objects.filter(Booking_vehicle=vehicle)
            for j in l:
                if ('Booking' in j[1]):
                    for ids in j[1]['Booking']:
                        if ('vehicle' in j[1]['Booking'][ids]):
                            if (j[1]['Booking'][ids]['vehicle'] == name_id):
                                books.append([j[1]['name'],j[1]['Booking'][ids],j[0]])


        except:
            books  = [-1]
            # print '----for vehicles-->'+str(name_id)+'<-------'
        vehicle_context = {p.key():p.val() for p in vehicle.each() if p.val() != None}
        print vehicle_context
        raw_latlon = vehicle_context['Coordinates']['P1'].split("|")
        ru = []
        

        if raw_latlon[0] == 'None' :
            ru = [[float(vehicle_context['latitude']),float(vehicle_context['longitude'])]]
        else :
            for k in range(len(raw_latlon)) :
                ru.append(raw_latlon[k].split(","))
                ru[k] = map(float,ru[k])
            
        context = {
        #"vehi_driver":vehi_driver,
        "vehi": vehicle_context,
        "bookings":books,
        "path":ru,
        }
        # context['vehi'] = filter(lambda a: a!= None, context['vehi'])
        #print ru
        return render(request,"Transport/vehicle.html",context)

@login_required
def update_driver(request,name_id):
    if(request.method == "POST"):
        form = UpdateDriver(request.POST)
        if form.is_valid():
            drivername = form.cleaned_data['drivername']
            driveremail = form.cleaned_data['driveremail']
            driveraddr = form.cleaned_data['driveraddr']
            driverphone = form.cleaned_data['driverphone']

            db.child("My_user").child("Driver").child(name_id).update({"Driver_name":drivername, "Driver_email":driveremail,"Driver_address":driveraddr,"phone":driverphone})
            # print 'yes__soka'   

            return HttpResponseRedirect('/Transport/allvehicles')
    else:
        # print 
        form = UpdateDriver()
    return render(request, "Transport/update_driver.html",{'form':form,'name':name_id})

@login_required
def passenger_details(request,name_id):                         #Details of passenger with id name_id

        users = db.child("My_user/Rider/"+str(name_id)).get()
        l = {p.key():p.val() for p in users.each() if p.val() != None}

        bo2 = db.child("My_user/Rider/Bookings").get()
        l2 = [p.val() for p in bo2.each() if p.val() != None]

        books = []
        books2 = []
        try:
            for j in l:
                if (j=='Booking'):
                    for ids in l['Booking']:
                        books.append(l['Booking'][ids])
            # bookings  = Booking.objects.filter(Bookinging_passenger=passenger)
            # print books
            for j in l2 :
                if (j['email'] == l['email']):
                    books2.append(j)
            
            print books2
            
        except:
            books  = []
            books2 = []
            # print books
            # print '----->'+str(name_id)+'<-------'

        context = {
        "users" : l,
        "bookings": books,
        "l2" : books2
        }

        return render(request,"Transport/passenger.html",context)

@login_required
def aboutus(request):
    return render(request,"Transport/aboutus.html",{})

website/Transport/templates/Transport1/allvehicles.html
{% extends 'Transport/base_visitor1.html' %}
{% block title %}Booking{% endblock %}
{% block login_active %}active{% endblock %}
{% block body %}
<!DOCTYPE html>
<html>
  <head>
    <style>
       #map {
        height: 400px;
        width: 100%;
       }
    </style>
  </head>
  <body>
  <h1>All vehicles</h1>
    <div id="map"></div>
    <script>
      function initMap() {
        var positions=[];
        {% for details in active_vehicles %}
        positions.push([{{details.vehicle_latitude}},{{details.vehicle_longitude}},{{details.id}},]);
        {% endfor %}
        var uluru = new google.maps.LatLng(positions[0][0], positions[0][1]);
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: uluru
        });
        var marker;
        for( var i = 0; i < positions.length; i++ ) {
          var positioned = new google.maps.LatLng(positions[i][0], positions[i][1]);
          marker = new google.maps.Marker({
            position: positioned,
            map: map,
            url:"{% url 'Transport:driver_accounts' %}"+positions[i][2]+"/"
          });
          google.maps.event.addListener(marker, 'click', function() {
            window.location.href = this.url;
          });
        }
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJ15BbQwlN0XqfqqeNY6uWNkZt0KtbfP4&callback=initMap">
    </script>
  </body>
</html>
{%endblock%}

website/Transport/templates/Transport1/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}IIITS-Transports{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'Transport/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'Transport/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Transport:index' %}">Transportation</a>
        </div>
        
	</div>

        <!-- Items -->
	<div class="collapse navbar-collapse" id="topNavBar">
		<!--<ul class="nav navbar-nav">-->
		<ul class="nav navbar-nav nav-bar-left">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'Transport:Booking' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Booking</a></li>
                <li><a href="{% url 'Transport:vehicle_details' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; vehicle_details</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'Transport:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/Transport/templates/Transport1/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Transportion{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'Transport/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'Transport/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Transport:index' %}">Transportion</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'Transport:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'Transport:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/Transport/templates/Transport1/base_visitor1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Transportation{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'Transport/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'Transport/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'Transport:index' %}">Transportion</a>
            <a class="navbar-brand" href="{% url 'Transport:allpassengers' %}">Passengers</a>
            <a class="navbar-brand" href="{% url 'Transport:alldrivers' %}">Drivers</a>
            <a class="navbar-brand" href="{% url 'Transport:allvehicles' %}">Vehicles</a>

            <!--<a class="navbar-brand" href="{% url 'Transport:index' %}">Track</a>-->
        </div>

	<!-- Items -->
	<div class="collapse navbar-collapse" id="topNavBar">
		<ul class="nav navbar-nav navbar-right">
			<li>
			<a href="{% url 'Transport:logout_user' %}">
				<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout : {{request.user.username}}
			</a>
			</li>
		</ul>
	</div>



        </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/Transport/templates/Transport1/driver.html
{{context['driver']}}

website/Transport/templates/Transport1/drivers.html
{%for driver in drivers%}
	{{driver.Driver_My_user.My_user_name}}
	{{driver.Driver_currentVehicle.Vehicle_name}}
{%endfor%}

website/Transport/templates/Transport1/index.html
{% extends 'Transport/base_visitor1.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<h3>Wel-come to transportation</h3>
{% endblock %}

website/Transport/templates/Transport1/login.html
{% extends 'Transport/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'Transport:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

			<div class="form-group">
				<div class="col-sm-10">
				<a href="{% url 'Transport:register' %}">Forgot Password...</a>
				</div>
			</div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'Transport:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

website/Transport/templates/Transport1/passenger.html
{{context['passenger']}}

website/Transport/templates/Transport1/passengers.html
{%for passenger in passengers%}
	{{passenger.Passenger_My_user.My_user_name}}
{%endfor%}

website/Transport/templates/Transport1/register.html
{% extends 'Transport/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'Transport/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'Transport:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

website/Transport/templates/Transport1/vehicle.html
{{context['vehicle']}}

website/Transport/templates/Transport1/vehicles.html
{%for vehicle in vehicles%}
	{{vehicle.Vehicle_name}}
	{%endfor%}