website/Transport/urls.py
from django.conf.urls import url
from . import views
from mylogin import views as logviews
app_name = 'Transport'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', logviews.register, name='register'),
    url(r'^login/$', logviews.login_user, name='login_user'),
    url(r'^register/success/$',logviews.register_success),
    url(r'^logout_user/$', logviews.logout_user, name='logout_user'),
    #url(r'logout_user/$', views.new_login, name='new_login'),

    url(r'^allpassengers/',views.allpassengers, name='allpassengers'),    
    url(r'^alldrivers/',views.alldrivers, name='alldrivers'),
    url(r'^allvehicles/',views.allvehicles,name='allvehicles'),    
    url(r'^passenger_details/(?P<name_id>[1-6])/$',views.passenger_details,name="passenger_details"),
    url(r'^driver_details/(?P<name_id>car_[1-6])/$',views.driver_details,name="driver_details"),#### not used....
    url(r'^vehicle_details/(?P<name_id>car_[1-6])/$',views.vehicle_details,name="vehicle_details"),
    ####
    url(r'^update_driver/(?P<name_id>car_[1-6])/$',views.update_driver,name="update_driver"),
    url(r'^aboutus/$',views.aboutus,name='aboutus'),
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Transport/', include('Transport.urls')),
    url(r'^', include('Transport.urls')),
    #url(r'^reset/password_reset/$','django.contrib.auth.views.password_reset',name = 'reset_password_reset1'),
    url(r'^locate/', include('locate_me.urls')),
]

website/Transport/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import Permission, User
from django.db import models
from datetime import datetime
#from geoposition.fields import GeopositionField

# Create your models here.

class My_user(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    My_user_gender      = models.CharField(max_length=1, choices=GENDER_CHOICES,default=None)
    My_user_name        = models.CharField(max_length=250,default=None)
    My_user_phone       = models.IntegerField(default=None)
    My_user_addr        = models.CharField(max_length=250,default=None)
    My_user_email       = models.CharField(max_length=250,default=None)
    My_user_dateOfBirth = models.DateField(default=None,null=True)#To know the age of user
    def __str__(self):
        return '#'+self.My_user_name

class Vehicle(models.Model):#Stores information about vehicles
    Vehicle_name      = models.CharField(max_length=200,default=None)
    Vehicle_latitude  = models.FloatField(default=None)#latitude of vehicle
    Vehicle_longitude = models.FloatField(default=None)#longitude of vehicle
    Vehicle_rc        = models.CharField(max_length=200,default=None)#rc of the vehicle
    Vehicle_active    = models.BooleanField(default=None)#status of vehicle
    def __str__(self):
        return '@'+self.Vehicle_rc

class Driver(models.Model):#stores all driver details
    Driver_My_user        = models.ForeignKey(My_user,on_delete=models.CASCADE, default=0,blank=True)#to get all details from My user
    Driver_currentVehicle = models.ForeignKey(Vehicle,on_delete=models.CASCADE, default=0)
    Driver_liscence       = models.CharField(max_length=20,default=None)
    Driver_longitude      = models.FloatField(default=None,null=True)#longitude of driver
    Driver_latitude       = models.FloatField(default=None,null=True)#latitude  of driver
    #driver_currentVehicle gets current detail of vehicle driver
    def __str__(self):
        return '!'+self.Driver_My_user.My_user_name

class Passenger(models.Model):#stores all passangers details
    Passenger_My_user   = models.ForeignKey(My_user,on_delete=models.CASCADE, default=0)#to get all details from My user
    Passenger_latitude  = models.FloatField(default=None)#current latitude of passenger
    Passenger_longitude = models.FloatField(default=None)#current longitude of passenger
    Passenger_active    = models.BooleanField(default=None)#
    def __str__(self):
        return '$'+self.Passenger_My_user.My_user_name

class Valid_stop(models.Model):#This model stores all the valid stops
    Valid_stop_name      = models.CharField(max_length=50,default=None)#name of the stops
    Valid_stop_latitude  = models.FloatField(default=None)#latitude of valid stops
    Valid_stop_longitude = models.FloatField(default=None)#longitude of valid stops
    def __str__(self):
        return '%'+self.Valid_stop_name

class Booking(models.Model):#Stores all the information about bookings
    #Booking_startpoint  = models.ForeignKey(Valid_stop,default=0,on_delete=models.CASCADE,related_name='%(class)s_starting_point')#starting point of booking
    #Booking_destination = models.ForeignKey(Valid_stop, default=0,on_delete=models.CASCADE,related_name='%(class)s_destination_point')#ending point of booking
    Booking_startpoint  = models.CharField(max_length = 50,default=None)#starting point of booking
    Booking_destination = models.CharField(max_length = 50,default=None)#ending point of booking
    Booking_date        = models.DateTimeField(auto_now_add=True)
    Booking_passenger   = models.ForeignKey(Passenger, default=0,on_delete=models.CASCADE)#passanger
    Booking_vehicle     = models.ForeignKey(Vehicle,null=True,on_delete=models.CASCADE,blank=True)#vehicle booked
    Booking_status      = models.CharField(max_length=50,default='Pending')
    #booking_driver      = models.ForeignKey(driver,on_delete=models.CASCADE)#driver of the vehicle at the time of booking
    def __str__(self):
        return '^'+str(self.Booking_date)

class updatedriver(models.Model):
    drivername = models.CharField(max_length =100,default = None)
    driveremail = models.CharField(max_length =100,default = None)
    driveraddr = models.CharField(max_length =100,default = None)
    driverphone = models.CharField(max_length =100,default = None)

website/Transport/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UpdateDriver(forms.ModelForm):
   	class Meta:
 		model = updatedriver
 		fields = ['drivername','driveremail','driveraddr','driverphone']
#forms.py

website/Transport/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from Transport.models import *
from Transport.forms import *
from django import forms
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import pyrebase
config = {
    "apiKey": "AIzaSyAQHHnCqr-3FajALfmpg19PS44fsB6XkBA",
    "authDomain": "itsystems-162415.firebaseapp.com",
    "databaseURL": "https://itsystems-162415.firebaseio.com",
    "storageBucket" : "itsystems-162415.appspot.com"
  };
firebase = pyrebase.initialize_app(config);
db = firebase.database()

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)

                return render(request, 'Transport/index.html')
    context = {
        "form": form,
    }
    return render(request, 'Transport/register.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'Transport/index.html')
            else:
                return render(request, 'mylogin/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'mylogin/login.html', {'error_message': 'Invalid login'})
    return render(request, 'Transport/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'Transport/login.html', context)


def new_login(request):
    return render(request,'Transport/loggyn.html',{})     

def index(request):

   if not request.user.is_authenticated():
    return render(request,'mylogin/login.html')

   else:
        fire_vehi = db.child("My_user/Driver/").get()
        fire_rider = db.child("My_user/Rider/").get()
        # drivers    = Driver.objects.all()  
        # vehicles   = Vehicle.objects.all()                       
        passengers  = [[p.key(),p.val()] for p in fire_rider.each()]
        passengers = filter(lambda a: a[1]!= None, passengers)
        context    = {
                    # "drivers"   :drivers,
                    # "passengers":passengers,
                    # "vehicles"  :vehicles,
                    "drivs" : [p.val() for p in fire_vehi.each()],
                    "riders"  : passengers

                 }
        context['drivs'] = filter(lambda a: a!= None, context['drivs'])
        # print passengers[0]
        return render(request,'Transport/index.html',context)

     
@login_required
def allpassengers(request):                                     #displays all passengers
    users = db.child("My_user/Rider").get()
    use = [[p.key(),p.val()] for p in users.each() if p.val() != None]
    context = {
    "users" : use
    }
    print use
    return render(request,"Transport/passengers.html",context)

@login_required
def alldrivers(request):                                        #display all drivers
    users = db.child("My_user/Driver/").get()
    context = {
    "users" : [p.val() for p in users.each()]
    }
    return render(request, "Transport/drivers.html",context)

@login_required
def allvehicles(request):
    vehicles = db.child("My_user/Driver/").get()
    # vehicles = Vehicle.objects.all()                            #gets all vehicle details
    #vehicles = Vehicle.objects.all().count();
    # print vehicles
    context  = {                    
        "vehicles":[p.val() for p in vehicles.each()],
    }
    return render(request,"Transport/vehicles.html",context)

@login_required
def driver_details(request,name_id):                            #Details of driver with name_id as id
    driver  = Driver.objects.get(id=name_id)
    context = {
    "driver" : driver,
    }
    return render(request,"Transport/driver.html",context)

@login_required
def vehicle_details(request,name_id):                           #Details of vehicle with id name_id
        #vehicle = Vehicle.objects.get(id=name_id)
        print name_id
        vehicle = db.child("My_user/Driver/"+str(name_id)).get()
        riders = db.child("My_user/Rider/").get()
        l = [[p.key(),p.val()] for p in riders.each()]
        l = filter(lambda a: a[1]!= None, l)
        books = []
        try:
            # bookings  = Booking.objects.filter(Booking_vehicle=vehicle)
            for j in l:
                if ('Booking' in j[1]):
                    for ids in j[1]['Booking']:
                        if ('vehicle' in j[1]['Booking'][ids]):
                            if (j[1]['Booking'][ids]['vehicle'] == name_id):
                                books.append([j[1]['name'],j[1]['Booking'][ids],j[0]])


        except:
            books  = [-1]
            # print '----for vehicles-->'+str(name_id)+'<-------'
        vehicle_context = {p.key():p.val() for p in vehicle.each() if p.val() != None}
        print vehicle_context
        raw_latlon = vehicle_context['Coordinates']['P1'].split("|")
        ru = []
        

        if raw_latlon[0] == 'None' :
            ru = [[float(vehicle_context['latitude']),float(vehicle_context['longitude'])]]
        else :
            for k in range(len(raw_latlon)) :
                ru.append(raw_latlon[k].split(","))
                ru[k] = map(float,ru[k])
            
        context = {
        #"vehi_driver":vehi_driver,
        "vehi": vehicle_context,
        "bookings":books,
        "path":ru,
        }
        # context['vehi'] = filter(lambda a: a!= None, context['vehi'])
        #print ru
        return render(request,"Transport/vehicle.html",context)

@login_required
def update_driver(request,name_id):
    if(request.method == "POST"):
        form = UpdateDriver(request.POST)
        if form.is_valid():
            drivername = form.cleaned_data['drivername']
            driveremail = form.cleaned_data['driveremail']
            driveraddr = form.cleaned_data['driveraddr']
            driverphone = form.cleaned_data['driverphone']

            db.child("My_user").child("Driver").child(name_id).update({"Driver_name":drivername, "Driver_email":driveremail,"Driver_address":driveraddr,"phone":driverphone})
            # print 'yes__soka'   

            return HttpResponseRedirect('/Transport/allvehicles')
    else:
        # print 
        form = UpdateDriver()
    return render(request, "Transport/update_driver.html",{'form':form,'name':name_id})

@login_required
def passenger_details(request,name_id):                         #Details of passenger with id name_id

        users = db.child("My_user/Rider/"+str(name_id)).get()
        l = {p.key():p.val() for p in users.each() if p.val() != None}

        bo2 = db.child("My_user/Rider/Bookings").get()
        l2 = [p.val() for p in bo2.each() if p.val() != None]

        books = []
        books2 = []
        try:
            for j in l:
                if (j=='Booking'):
                    for ids in l['Booking']:
                        books.append(l['Booking'][ids])
            # bookings  = Booking.objects.filter(Bookinging_passenger=passenger)
            # print books
            for j in l2 :
                if (j['email'] == l['email']):
                    books2.append(j)
            
            print books2
            
        except:
            books  = []
            books2 = []
            # print books
            # print '----->'+str(name_id)+'<-------'

        context = {
        "users" : l,
        "bookings": books,
        "l2" : books2
        }

        return render(request,"Transport/passenger.html",context)

@login_required
def aboutus(request):
    return render(request,"Transport/aboutus.html",{})

website/Transport/templates/Transport/aboutus.html
{% extends 'Transport/base.html' %}

{% block content1%}<title>About Us</title>{% endblock %}

{% block change %}
<div class="col-sm-12 col-md-6">
    <div class="panel panel-default" style="position:fixed;left:29%;top:9%;width:57%; height: 10%;background-color:#F73B46;" >
        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h3 style="position: fixed; left: 31%; top:8%;"><b>A.C.Sreedhar Reddy : </b><i> Website-design, Project-design</i><br><br></h3>
        </div>
    </div>
    <div class="panel panel-default" style="position:fixed;left:29%;top:19%;width:57%; height: 10%;background-color:#F73B90;" >
        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h3 style="position: fixed; left: 31%; top:18%;"><b>B.Vamshi : </b><i> Code-testing, Hardware-helper</i><br><br></h3>
        </div>
    </div>
    <div class="panel panel-default" style="position:fixed;left:29%;top:29%;width:57%; height: 10%;background-color:#F73BDD;" >
        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h3 style="position: fixed; left: 31%; top:28%;"><b>D.Maniteja : </b><i>Hardware-testing, Circuit-design</i><br><br></h3>
        </div>
    </div>
    <div class="panel panel-default" style="position:fixed;left:29%;top:39%;width:57%; height: 10%;background-color:#BE3BF7;" >
        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h3 style="position: fixed; left: 31%; top:38%;"><b>K.Jagadeesh :</b><i> Circuit-testing, Hardware-testing</i><br><br></h3>
        </div>
    </div>
    <div class="panel panel-default" style="position:fixed;left:29%;top:49%;width:57%; height: 10%;background-color:#493BF7;" >
        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h3 style="position: fixed; left: 31%; top:48%;"><b>K.Sai Krishna Maurya : </b><i> Android-deveoper, Cloud Management </i><br><br></h3>
        </div>
    </div>
    <div class="panel panel-default" style="position:fixed;left:29%;top:59%;width:57%; height: 10%;background-color:#3BC7F7;" >
        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h3 style="position: fixed; left: 31%; top:58%;"><b>P.Vamsi Krishna : </b><i> Android-design, Hardware-testing</i><br><br></h3>
        </div>
    </div>
    <div class="panel panel-default" style="position:fixed;left:29%;top:69%;width:57%; height: 10%;background-color:#28EE3D;" >
        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h3 style="position: fixed; left: 31%; top:68%;"><b>B.Chiranjith : </b><i> Android-design, Hardware-integration</i><br><br></h3>
        </div>
    </div>
    <div class="panel panel-default" style="position:fixed;left:29%;top:79%;width:57%; height: 10%;background-color:#E2EF12;" >
        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h3 style="position: fixed; left: 31%; top:78%;"><b>D.Srikanth : </b><i> Hardware & Software integration</i><br><br></h3>
        </div>
    </div>
    <div class="panel panel-default" style="position:fixed;left:29%;top:89%;width:57%; height: 10%;background-color:#FF836A;" >
        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h3 style="position: fixed; left: 31%; top:88%;"><b>M.Krishna Chait<u>h</u>anya : </b><i>Backend-developer & Cloud management</i><br><br></h3>
        </div>
    </div>
</div>

{% endblock %}

website/Transport/templates/Transport/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {%block content1%}
    {%endblock%}

    {% load staticfiles %}<!--load static files-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

   <!--  <title>Transbook</title> -->

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'Transport/vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'Transport/vendor/metisMenu/metisMenu.min.css'%}" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="{% static 'Transport/vendor/datatables-plugins/dataTables.bootstrap.css'%}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{% static 'Transport/vendor/datatables-responsive/dataTables.responsive.css'%}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'Transport/dist/css/sb-admin-2.css'%}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'Transport/vendor/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>
{%block mapcontent%}

{%endblock%}
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;position :fixed; width: 100%;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Transport">TRANSBOOK</a>
            </div>
            <!-- /.navbar-header -->


            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li><a href="{% url 'Transport:logout_user' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" style="position : fixed" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="/Transport"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="{% url 'Transport:allpassengers' %}"><i class="fa fa-street-view" aria-hidden="true"></i>
 Passengers</a>
                        </li>
                        <li>
                            <a href="{% url 'Transport:alldrivers' %}"><i class="fa fa-empire" aria-hidden="true"></i>
Drivers</a>
                        </li>
                        <li>
                            <a href="{% url 'Transport:allvehicles' %}"><i class="fa fa-car" aria-hidden="true"></i>
 Vehicles</a>
                        </li>
                        <li>
                            <a href="{% url 'Transport:aboutus' %}"><i class="fa fa-star" aria-hidden="true"></i>
 About Us</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <!-- <div class="col-lg-12"> -->
                <!-- <div id="map"></div> -->
                {%block mapid%}
                {%endblock%}
                {%block change%}
                {%endblock%}
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->

            <!-- /.row -->

            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
        
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
      <script src="{% static 'Transport/vendor/jquery/jquery.min.js'%}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'Transport/vendor/bootstrap/js/bootstrap.min.js'%}"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="{% static 'Transport/vendor/metisMenu/metisMenu.min.js'%}"></script>

    <!-- DataTables JavaScript -->
    <script src="{% static 'Transport/vendor/datatables/js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static 'Transport/vendor/datatables-plugins/dataTables.bootstrap.min.js'%}"></script>
    <script src="{% static 'Transport/vendor/datatables-responsive/dataTables.responsive.js'%}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'Transport/dist/js/sb-admin-2.js'%}"></script>
    <script src="{% static 'Transport/dist/js/map.js'%}"></script>
    {%block drivertable%}
    {%endblock%}
</body>

</html>

website/Transport/templates/Transport/drivers.html
{% extends 'Transport/base.html'%}
<html>
    {% load staticfiles %}
    <!--load static files-->
    
     {%block mapid%}
     <title>Drivers</title>
      <h1 class="page-header"></h1>

            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Drivers
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        
                                        <th>Name</th>
                                        <th>Phone</th>
                                        <th>Vehicle</th>
                                        <th>Vehicle no</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    {%for driver in users%}
                                    <tr class="odd gradeC">
                                                
                                        <td>{{driver.Driver_name}}</td>
                                        <td>{{driver.phone}}</td>
                                        <td><a href="/Transport/vehicle_details/{{driver.vehicle_name}}">{{driver.vehicle_name}}</a></td>
                                        <!-- <td>{{driver.vehicle_name}}</td> -->
                                        <td>{{driver.vehicle}}</td>
                                    </tr>
                                    {%endfor%}
                                    
                                </tbody>
                            </table>
                            <!-- /.table-responsive -->
                            
                        </div>
                        <!-- /.panel-body -->
                    </div>

                    </div>
                    </div>
    {%endblock%}

{%block drivertable%}

    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
    </script>

{%endblock%}

</html>

website/Transport/templates/Transport/passengers.html
{%extends 'Transport/base.html'%}
<html lang="en">
   {% load staticfiles %}<!--load static files-->
        {%block mapid%}
        <title>Passengers</title>
        <h1 class="page-header"></h1>

            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Passengers
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Mobile</th>
                                        <th>e-mail</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {%for ind in users%}
                                        <tr class="odd gradeX">
                                            <td><a href="/Transport/passenger_details/{{ind.0}}">{{ind.1.name}}</a></td>
                                            <td>{{ind.1.phone}}</td>
                                            <td>{{ind.1.email}}</td>
                                        </tr>
                                    {%endfor%}

                                </tbody>
                            </table>
                            <!-- /.table-responsive -->

                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
                </div>
        {%endblock%}
    {%block drivertable%}

    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
    </script>
{%endblock%}

</html>

website/Transport/templates/Transport/update_driver.html
{% extends 'Transport/base.html' %}
 {% block content1%}<title>Update_Driver</title>{% endblock %}
<!--  {% block login_active %}active{% endblock %} -->
 {% block change %}
<div class="col-sm-12 col-md-6">
    <div class="panel panel-default" style="position:fixed;left:35%;top:13%;width:47%; background-color:#668D91;" >

        <div class="panel-body" style="width:221%;top:110px;height:436px;left:34%;position:static;">
            <h2 style="position: fixed; left: 40%;">Update Driver Information for {{name}}:<br><br></h2>
            <form method="POST" class="post-form" style="position:fixed; right:12%; top: 34%; width: 41%;">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default" style="position: fixed; left: 47%; top: 67%;">Submit</button>
        </form>
        </div>
    </div>
</div>

{% endblock %}